### PR TITLE
feat: options for custom report deployment

### PR DESCRIPTION
**Pull request by goldst**
First of all, thank you for this action! We found it to be incredibly useful for our visual regression tests.

We don't use [reg-actions.pages.dev](reg-actions.pages.dev) but instead deploy the report to a different URL. For this, we (@NejiGhazouani and me) made some modifications to `reg-actions`:
- We added an optional option for a **custom URL for the comment**. If it is not provided, the action behaves as it did before.
- We added an optional option for **report HTML output location**. This report can then be used for other actions. If it is not provided, the action behaves as it did before.

The report HTML output location feature requires access to some files from `reg-cli`, thus the build commands had to be adjusted.

Perhaps this is something that could be useful to other people too?

### CODE REVIEW

**Comment by goldst** [comment]
@bokuweb could you give some short feedback on this? Thanks!

**Comment by bokuweb** [comment]
@goldst Sorry. I missed it, I'll check it later

**Review by bokuweb — APPROVED** [review]
LGTM

@goldst Sorry for late. I'll merge it `develop` branch for now.
You can try to use latest feature with `bokuweb/reg-actions@rc`.

**Comment by bokuweb** [comment]
@goldst @NejiGhazouani This PR is merged into main. Thanks four your great work.

**Pull request merged**
